#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UsbSerial.Resource", IsApplication=true)]

namespace UsbSerial
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Hoho.Android.UsbSerial.Resource.String.ApplicationName = global::UsbSerial.Resource.String.ApplicationName;
			global::Hoho.Android.UsbSerial.Resource.String.Hello = global::UsbSerial.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon1 = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int consoleText = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int demoScroller = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int demoTitle = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int deviceList = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int plotView1 = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int progressBar = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int progressBarTitle = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int separator = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int sleepButton = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int startButton = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int stopButton = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int serial_console = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int refreshing = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sleep = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int wakeup = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int device_filter = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
